trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
- 
- task: CmdLine@2
  inputs:
    script: |
      dotnet build --configuration $(buildConfiguration)
      
      displayName: "build configuration: $(buildConfiguration)